# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('host_ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('project_name', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('service_name', models.CharField(max_length=32, verbose_name='\u670d\u52a1\u540d')),
                ('start_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4')),
                ('stop_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u505c\u6b62\u547d\u4ee4')),
                ('restart_file', models.CharField(max_length=128, verbose_name='\u91cd\u542f\u547d\u4ee4')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(to='start_opt.Service'),
        ),
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ManyToManyField(to='start_opt.Project'),
        ),
    ]
