# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_opt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_dir',
            field=models.CharField(default=2, max_length=64, verbose_name='\u9879\u76ee\u76ee\u5f55'),
            preserve_default=False,
        ),
    ]
